language: python
python:
  - "3.7"
before_install:
  - mv .travis.secrets.yaml homeassistant/secrets.yaml
  - sudo apt-get install -y libudev-dev
install:
  - pip3 install homeassistant
script:
  - hass -c homeassistant --script check_config