- platform: burze_dzis_net
  api_key: !secret burze_dzis_net_api_key
  warnings:
    - frost_warning
    - heat_warning
    - wind_warning
    - precipitation_warning
    - storm_warning
    - tornado_warning
  storms_nearby:
    radius: 30
- platform: dlink_hnap
  name: Toilet water leak sensor
  host: 10.10.10.41
  type: water
  username: Admin
  password: !secret dlink_toilet_water_sensor_pincode
- platform: dlink_hnap
  name: Kitchen water leak sensor
  host: 10.10.10.42
  type: water
  username: Admin
  password: !secret dlink_kitchen_water_sensor_pincode
- platform: dlink_hnap
  name: Bathroom water leak sensor
  host: 10.10.10.112
  type: water
  username: Admin
  password: !secret dlink_bathroom_water_sensor_pincode
- platform: template
  sensors:
    living_room_cam_motion:
      friendly_name: Living room cam motion
      device_class: motion
      entity_id: camera.living_room_cam
      value_template: "{{ is_state('camera.living_room_cam', 'motion') }}"
      delay_off: 
          seconds: 60
    hallway_entrance_cam_motion:
      friendly_name: Hallway entrance cam motion
      device_class: motion
      entity_id: camera.hallway_entrance_cam
      value_template: "{{ is_state('camera.hallway_entrance_cam', 'motion') }}"
      delay_off: 
          seconds: 60
    bathroom_motion:
      friendly_name: Bathroom motion
      device_class: motion
      value_template: "{{ is_state('binary_sensor.bathroom_shower_motion_sensor_sensor', 'on') or is_state('binary_sensor.bathroom_multisensor_motion', 'on') or is_state('sensor.bathroom_multisensor_burglar', '8') }}"
      delay_off:
          seconds: 60
    shower_in_use:
      value_template: "{{ states('sensor.bathroom_multisensor_relative_humidity') | float > 60 or states('sensor.bathroom_humidity') | float > 60 }}"
    toilet_sonos_is_master:
      value_template: "{{ 'media_player.toilet' == state_attr('media_player.toilet', 'group_members')[0] }}"
    bathroom_sonos_is_master:
      value_template: "{{ 'media_player.bathroom' == state_attr('media_player.bathroom', 'group_members')[0] }}"
    living_room_sonos_is_master:
      value_template: "{{ 'media_player.living_room' == state_attr('media_player.living_room', 'group_members')[0] }}"
    kitchen_sonos_is_master:
      value_template: "{{ 'media_player.kitchen' == state_attr('media_player.kitchen', 'group_members')[0] }}"
    office_sonos_is_master:
      value_template: "{{ 'media_player.office' == state_attr('media_player.office', 'group_members')[0] }}"
    bedroom_sonos_is_master:
      value_template: "{{ 'media_player.bedroom' == state_attr('media_player.bedroom', 'group_members')[0] }}"
    toilet_sonos_roon_is_master:
      value_template: "{{ 'media_player.toilet_sonos_roon' == state_attr('media_player.toilet_sonos_roon', 'group_members')[0] }}"
    bathroom_sonos_roon_is_master:
      value_template: "{{ 'media_player.bathroom_sonos_roon' == state_attr('media_player.bathroom_sonos_roon', 'group_members')[0] }}"
    living_room_amplifier_roon_is_master:
      value_template: "{{ 'media_player.living_room_amplifier_roon' == state_attr('media_player.living_room_amplifier_roon', 'group_members')[0] }}"
    kitchen_sonos_roon_is_master:
      value_template: "{{ 'media_player.kitchen_sonos_roon' == state_attr('media_player.kitchen_sonos_roon', 'group_members')[0] }}"
    office_sonos_roon_is_master:
      value_template: "{{ 'media_player.office_sonos_roon' == state_attr('media_player.office_sonos_roon', 'group_members')[0] }}"
    bedroom_sonos_roon_is_master:
      value_template: "{{ 'media_player.bedroom_sonos_roon' == state_attr('media_player.bedroom_sonos_roon', 'group_members')[0] }}"
