- platform: braviatv
  host: 10.10.10.8
  name: Living room TV
- platform: braviatv
  host: 10.10.10.53
  name: Bedroom TV
- platform: denon
  host: 10.10.10.70
  #show_all_sources: true
  #zones:
  #  - zone: Zone2