- platform: xboxone
  device: !secret xbox_live_device_id
  ip_address: 10.10.10.79
  name: XBOX ONE X
- platform: braviatv
  host: 10.10.10.8
  name: Living room TV
- platform: braviatv
  host: 10.10.10.53
  name: Bedroom TV
- platform: androidtv
  host: 10.10.10.87
  name: SHIELD Android TV
- platform: androidtv
  host: 10.10.10.8
  name: Living room Android TV
- platform: androidtv
  host: 10.10.10.53
  name: Bedroom Android TV
- platform: denon
  host: 10.10.10.70
  name: Denon AVC-X6500H Receiver
  #show_all_sources: true
  #zones:
  #  - zone: Zone2
- platform: kodi
  name: Living room Kodi
  host: 10.10.10.87
  port: 8779
  tcp_port: 9090
  username: !secret kodi_username
  password: !secret kodi_password
  enable_websocket: true
  turn_on_action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: !secret shield_mac_address
  turn_off_action:
    service: kodi.call_method
    data:
      entity_id: media_player.living_room_kodi
      method: System.Shutdown
