- platform: kodi
  name: Notify Living room Kodi
  host: 10.10.10.87
  port: 8779
  username: !secret kodi_username
  password: !secret kodi_password

- platform: nfandroidtv
  host: 10.10.10.87
  name: SHIELD Android TV
- platform: nfandroidtv
  host: 10.10.10.8
  name: Living room Android TV
- platform: nfandroidtv
  host: 10.10.10.53
  name: Bedroom Android TV

- name: residents
  platform: group
  services:
    - service: mobile_app_sm_g998b # Pawel
    - service: mobile_app_iphone # Daria

- name: all_mobile
  platform: group
  services:
    - service: mobile_app_sm_g998b # Pawel
    - service: mobile_app_iphone # Daria
    - service: mobile_app_archos_101_oxygen_4g # Smart Tablet
    - service: mobile_app_ipad # Smart Tablet iPad
    - service: mobile_app_sm_n910c # Smart Phone

- name: everything_without_voice
  platform: group
  services:
    - service: mobile_app_sm_g998b # Pawel
    - service: mobile_app_iphone # Daria
    - service: mobile_app_archos_101_oxygen_4g # Smart Tablet
    - service: mobile_app_ipad # Smart Tablet iPad
    - service: mobile_app_sm_n910c # Smart Phone
    - service: notify_living_room_kodi
    - service: alexa_media
      data:
        target: media_player.living_room_echo
        data:
          type: push
          method: all

- name: everything
  platform: group
  services:
    - service: mobile_app_sm_g998b # Pawel
    - service: mobile_app_iphone # Daria
    - service: mobile_app_archos_101_oxygen_4g # Smart Tablet
    - service: mobile_app_ipad # Smart Tablet iPad
    - service: mobile_app_sm_n910c # Smart Phone
    - service: notify_living_room_kodi
    - service: alexa_media
      data:
        target: group.all_alexa
        data:
          type: tts
          method: all
    - service: alexa_media
      data:
        target: media_player.living_room_echo
        data:
          type: push
          method: all
