- platform: template
  switches:
    watch_movie:
      friendly_name: Watch a movie
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Shield TV') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: Shield TV
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
      icon_template: >-
        {% if is_state_attr('remote.harmony_hub', 'current_activity', 'Shield TV') %}
          mdi:filmstrip
        {% else %}
          mdi:filmstrip-off
        {% endif %}

    play_game:
      friendly_name: Play a game
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Play a Game') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: Play a Game
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
      icon_template: mdi:gamepad-variant


    heat_living_room:
      friendly_name: Heat living room
      entity_id: climate.living_room
      value_template: "{{ is_state('climate.living_room', 'heat') }}"
      turn_on:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.living_room
          hvac_mode: heat
      turn_off:
        service: climate.turn_off
        data:
          entity_id: climate.living_room
      icon_template: >-
        {% if is_state('climate.living_room', 'heat') %}
          mdi:radiator
        {% else %}
          mdi:radiator-off
        {% endif %}

    heat_kitchen:
      friendly_name: Heat kitchen
      entity_id: climate.kitchen
      value_template: "{{ is_state('climate.kitchen', 'heat') }}"
      turn_on:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.kitchen
          hvac_mode: heat
      turn_off:
        service: climate.turn_off
        data:
          entity_id: climate.kitchen
      icon_template: >-
        {% if is_state('climate.kitchen', 'heat') %}
          mdi:radiator
        {% else %}
          mdi:radiator-off
        {% endif %}

    heat_bathroom:
      friendly_name: Heat bathroom
      entity_id: climate.bathroom
      value_template: "{{ is_state('climate.bathroom', 'heat') }}"
      turn_on:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.bathroom
          hvac_mode: heat
      turn_off:
        service: climate.turn_off
        data:
          entity_id: climate.bathroom
      icon_template: >-
        {% if is_state('climate.bathroom', 'heat') %}
          mdi:radiator
        {% else %}
          mdi:radiator-off
        {% endif %}

    heat_office:
      friendly_name: Heat office
      entity_id: climate.office
      value_template: "{{ is_state('climate.office', 'heat') }}"
      turn_on:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.office
          hvac_mode: heat
      turn_off:
        service: climate.turn_off
        data:
          entity_id: climate.office
      icon_template: >-
        {% if is_state('climate.office', 'heat') %}
          mdi:radiator
        {% else %}
          mdi:radiator-off
        {% endif %}

    heat_bedroom:
      friendly_name: Heat bedroom
      entity_id: climate.bedroom
      value_template: "{{ is_state('climate.bedroom', 'heat') }}"
      turn_on:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.bedroom
          hvac_mode: heat
      turn_off:
        service: climate.turn_off
        data:
          entity_id: climate.bedroom
      icon_template: >-
        {% if is_state('climate.bedroom', 'heat') %}
          mdi:radiator
        {% else %}
          mdi:radiator-off
        {% endif %}

    heat_bathroom_floor:
      friendly_name: Heat bathroom floor
      entity_id: climate.bathroom_floor
      value_template: "{{ is_state('climate.bathroom_floor', 'heat') }}"
      turn_on:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.bathroom_floor
          hvac_mode: heat
      turn_off:
        service: climate.turn_off
        data:
          entity_id: climate.bathroom_floor
      icon_template: >-
        {% if is_state('climate.bathroom_floor', 'heat') %}
          mdi:radiator
        {% else %}
          mdi:radiator-off
        {% endif %}

    heat_toilet_floor:
      friendly_name: Heat toilet floor
      entity_id: climate.toilet_floor
      value_template: "{{ is_state('climate.toilet_floor', 'heat') }}"
      turn_on:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.toilet_floor
          hvac_mode: heat
      turn_off:
        service: climate.turn_off
        data:
          entity_id: climate.toilet_floor
      icon_template: >-
        {% if is_state('climate.toilet_floor', 'heat') %}
          mdi:radiator
        {% else %}
          mdi:radiator-off
        {% endif %}

    heat_kitchen_floor:
      friendly_name: Heat kitchen floor
      entity_id: climate.kitchen_floor
      value_template: "{{ is_state('climate.kitchen_floor', 'heat') }}"
      turn_on:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.kitchen_floor
          hvac_mode: heat
      turn_off:
        service: climate.turn_off
        data:
          entity_id: climate.kitchen_floor
      icon_template: >-
        {% if is_state('climate.kitchen_floor', 'heat') %}
          mdi:radiator
        {% else %}
          mdi:radiator-off
        {% endif %}

    cool_living_room:
      friendly_name: Cool living room
      entity_id: climate.living_room_ac
      value_template: "{{ is_state('climate.living_room_ac', 'cool') }}"
      turn_on:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.living_room_ac
          hvac_mode: cool
      turn_off:
        service: climate.turn_off
        data:
          entity_id: climate.living_room_ac
      icon_template: mdi:snowflake

    cool_office:
      friendly_name: Cool office
      entity_id: climate.office_ac
      value_template: "{{ is_state('climate.office_ac', 'cool') }}"
      turn_on:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.office_ac
          hvac_mode: cool
      turn_off:
        service: climate.turn_off
        data:
          entity_id: climate.office_ac
      icon_template: mdi:snowflake

    cool_bedroom:
      friendly_name: Cool bedroom
      entity_id: climate.bedroom_ac
      value_template: "{{ is_state('climate.bedroom_ac', 'cool') }}"
      turn_on:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.bedroom_ac
          hvac_mode: cool
      turn_off:
        service: climate.turn_off
        data:
          entity_id: climate.bedroom_ac
      icon_template: mdi:snowflake


    living_room_cam_email:
      value_template: "{{ is_state_attr('camera.living_room_cam', 'email_enabled', true) }}"
      turn_on:
        service: camera.enable_email
        data:
          entity_id: camera.living_room_cam
      turn_off:
        service: camera.disable_email
        data:
          entity_id: camera.living_room_cam
      icon_template: >-
        {% if is_state_attr('camera.living_room_cam', 'email_enabled', true) %}
          mdi:email
        {% else %}
          mdi:email-outline
        {% endif %}
          
    living_room_cam_ftp:
      value_template: "{{ is_state_attr('camera.living_room_cam', 'ftp_enabled', true) }}"
      turn_on:
        service: camera.enable_ftp
        data:
          entity_id: camera.living_room_cam
      turn_off:
        service: camera.disable_ftp
        data:
          entity_id: camera.living_room_cam
      icon_template: >-
        {% if is_state_attr('camera.living_room_cam', 'ftp_enabled', true) %}
          mdi:filmstrip
        {% else %}
          mdi:filmstrip-off
        {% endif %}
        
    living_room_cam_ir_lights:
      value_template: "{{ is_state_attr('camera.living_room_cam', 'ir_lights_enabled', true) }}"
      turn_on:
        service: camera.enable_ir_lights
        data:
          entity_id: camera.living_room_cam
      turn_off:
        service: camera.disable_ir_lights
        data:
          entity_id: camera.living_room_cam
      icon_template: >-
        {% if is_state_attr('camera.living_room_cam', 'ir_lights_enabled', true) %}
          mdi:flashlight
        {% else %}
          mdi:flashlight-off
        {% endif %}
    hallway_entrance_cam_email:
      value_template: "{{ is_state_attr('camera.hallway_entrance_cam', 'email_enabled', true) }}"
      turn_on:
        service: camera.enable_email
        data:
          entity_id: camera.hallway_entrance_cam
      turn_off:
        service: camera.disable_email
        data:
          entity_id: camera.hallway_entrance_cam
      icon_template: >-
        {% if is_state_attr('camera.hallway_entrance_cam', 'email_enabled', true) %}
          mdi:email
        {% else %}
          mdi:email-outline
        {% endif %}
          
    hallway_entrance_cam_ftp:
      value_template: "{{ is_state_attr('camera.hallway_entrance_cam', 'ftp_enabled', true) }}"
      turn_on:
        service: camera.enable_ftp
        data:
          entity_id: camera.hallway_entrance_cam
      turn_off:
        service: camera.disable_ftp
        data:
          entity_id: camera.hallway_entrance_cam
      icon_template: >-
        {% if is_state_attr('camera.hallway_entrance_cam', 'ftp_enabled', true) %}
          mdi:filmstrip
        {% else %}
          mdi:filmstrip-off
        {% endif %}
        
    hallway_entrance_cam_ir_lights:
      value_template: "{{ is_state_attr('camera.hallway_entrance_cam', 'ir_lights_enabled', true) }}"
      turn_on:
        service: camera.enable_ir_lights
        data:
          entity_id: camera.hallway_entrance_cam
      turn_off:
        service: camera.disable_ir_lights
        data:
          entity_id: camera.hallway_entrance_cam
      icon_template: >-
        {% if is_state_attr('camera.hallway_entrance_cam', 'ir_lights_enabled', true) %}
          mdi:flashlight
        {% else %}
          mdi:flashlight-off
        {% endif %}
