- platform: template
  switches:
    cool_living_room:
      friendly_name: Cool living room
      entity_id: climate.living_room_ac
      value_template: "{{ is_state('climate.living_room_ac', 'cool') }}"
      turn_on:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.living_room_ac
          hvac_mode: cool
      turn_off:
        service: climate.turn_off
        data:
          entity_id: climate.living_room_ac
      icon_template: mdi:snowflake

    cool_office:
      friendly_name: Cool office
      entity_id: climate.office_ac
      value_template: "{{ is_state('climate.office_ac', 'cool') }}"
      turn_on:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.office_ac
          hvac_mode: cool
      turn_off:
        service: climate.turn_off
        data:
          entity_id: climate.office_ac
      icon_template: mdi:snowflake

    cool_bedroom:
      friendly_name: Cool bedroom
      entity_id: climate.bedroom_ac
      value_template: "{{ is_state('climate.bedroom_ac', 'cool') }}"
      turn_on:
        service: climate.set_hvac_mode
        data:
          entity_id: climate.bedroom_ac
          hvac_mode: cool
      turn_off:
        service: climate.turn_off
        data:
          entity_id: climate.bedroom_ac
      icon_template: mdi:snowflake


    living_room_cam_email:
      value_template: "{{ is_state_attr('camera.living_room_cam', 'email_enabled', true) }}"
      turn_on:
        service: camera.enable_email
        data:
          entity_id: camera.living_room_cam
      turn_off:
        service: camera.disable_email
        data:
          entity_id: camera.living_room_cam
      icon_template: >-
        {% if is_state_attr('camera.living_room_cam', 'email_enabled', true) %}
          mdi:email
        {% else %}
          mdi:email-outline
        {% endif %}
          
    living_room_cam_ftp:
      value_template: "{{ is_state_attr('camera.living_room_cam', 'ftp_enabled', true) }}"
      turn_on:
        service: camera.enable_ftp
        data:
          entity_id: camera.living_room_cam
      turn_off:
        service: camera.disable_ftp
        data:
          entity_id: camera.living_room_cam
      icon_template: >-
        {% if is_state_attr('camera.living_room_cam', 'ftp_enabled', true) %}
          mdi:filmstrip
        {% else %}
          mdi:filmstrip-off
        {% endif %}
        
    living_room_cam_ir_lights:
      value_template: "{{ is_state_attr('camera.living_room_cam', 'ir_lights_enabled', true) }}"
      turn_on:
        service: camera.enable_ir_lights
        data:
          entity_id: camera.living_room_cam
      turn_off:
        service: camera.disable_ir_lights
        data:
          entity_id: camera.living_room_cam
      icon_template: >-
        {% if is_state_attr('camera.living_room_cam', 'ir_lights_enabled', true) %}
          mdi:flashlight
        {% else %}
          mdi:flashlight-off
        {% endif %}
    hallway_entrance_cam_email:
      value_template: "{{ is_state_attr('camera.hallway_entrance_cam', 'email_enabled', true) }}"
      turn_on:
        service: camera.enable_email
        data:
          entity_id: camera.hallway_entrance_cam
      turn_off:
        service: camera.disable_email
        data:
          entity_id: camera.hallway_entrance_cam
      icon_template: >-
        {% if is_state_attr('camera.hallway_entrance_cam', 'email_enabled', true) %}
          mdi:email
        {% else %}
          mdi:email-outline
        {% endif %}
          
    hallway_entrance_cam_ftp:
      value_template: "{{ is_state_attr('camera.hallway_entrance_cam', 'ftp_enabled', true) }}"
      turn_on:
        service: camera.enable_ftp
        data:
          entity_id: camera.hallway_entrance_cam
      turn_off:
        service: camera.disable_ftp
        data:
          entity_id: camera.hallway_entrance_cam
      icon_template: >-
        {% if is_state_attr('camera.hallway_entrance_cam', 'ftp_enabled', true) %}
          mdi:filmstrip
        {% else %}
          mdi:filmstrip-off
        {% endif %}
        
    hallway_entrance_cam_ir_lights:
      value_template: "{{ is_state_attr('camera.hallway_entrance_cam', 'ir_lights_enabled', true) }}"
      turn_on:
        service: camera.enable_ir_lights
        data:
          entity_id: camera.hallway_entrance_cam
      turn_off:
        service: camera.disable_ir_lights
        data:
          entity_id: camera.hallway_entrance_cam
      icon_template: >-
        {% if is_state_attr('camera.hallway_entrance_cam', 'ir_lights_enabled', true) %}
          mdi:flashlight
        {% else %}
          mdi:flashlight-off
        {% endif %}
