- alias: Announce input announcement everywhere
  trigger:
    - platform: state
      entity_id: input_text.announcement
  action:
    - service_template:  >
      {% if states('input_text.announcement') %} script.announce_everywhere
      {% else %} script.do_nothing {% endif %}
      data_template:
        message: "{{ states.input_text.announcement.state }}"
    - service: input_text.set_value
      data_template:
        entity_id: input_text.announcement
        value: ""
