# Smart Bedtime Automations (Single Resident)

- alias: "Good Night: Secure House when in Bed"
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.eight_left_bed_presence
      to: 'on'
      for: "00:05:00" # 5 minutes to ensure you're actually settling in
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: lock.lock
      target:
        entity_id: lock.front_door
    - service: script.turn_off_everything
    - service: notify.level_info
      data:
        title: "Good Night"
        message: "House secured. Sleep well, Pawel!"

- alias: "Wake Up: Comfort Mode"
  trigger:
    - platform: state
      entity_id: sensor.eight_left_sleep_stage
      from: 'light'
      to: 'awake'
  condition:
    - condition: time
      after: "06:00:00"
      before: "11:00:00"
  action:
    - service: script.turn_on_heating_everywhere_except_bedroom_and_office
