# Cinema Mode Automation

- alias: 'Cinema Mode: Start'
  trigger:
    - platform: state
      entity_id:
        - media_player.xboxone
        - media_player.shield_plex
        - media_player.living_room_kodi
        - media_player.living_room_android_tv
      to: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.movie_dinner
    - service: script.stop_vacuum

- alias: 'Cinema Mode: Pause/Stop'
  trigger:
    - platform: state
      entity_id:
        - media_player.xboxone
        - media_player.shield_plex
        - media_player.living_room_kodi
        - media_player.living_room_android_tv
      from: 'playing'
      to:
        - 'paused'
        - 'idle'
        - 'off'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.living_room_dimmed_for_pause
