# Bedroom door sensor

- alias: Turn bedroom lights on door open
  trigger:
    platform: state
    entity_id: sensor.bedroom_door_opening_sensor_access_control
    from: '23'
    to: '22'
  condition:
      condition: or  # 'when dark' condition: either after sunset or before sunrise - equivalent to a state condition on `sun.sun` of `below_horizon`
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
  action:
    service: light.turn_on
    entity_id: light.bedroom_lights


- alias: Say welcome on bedroom door open
  trigger:
    platform: state
    entity_id: sensor.bedroom_door_opening_sensor_access_control
    from: '23'
    to: '22'
  action:
    service: tts.google_say
    entity_id: "media_player.bedroom"
    data:
      message: 'Welcome to the bedroom!'

# Office door sensor

- alias: Turn office lights on door open
  trigger:
    platform: state
    entity_id: sensor.office_door_opening_sensor_access_control
    from: '23'
    to: '22'
  condition:
      condition: or  # 'when dark' condition: either after sunset or before sunrise - equivalent to a state condition on `sun.sun` of `below_horizon`
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
  action:
    service: light.turn_on
    entity_id: light.office_lights

- alias: Say welcome on office door open
  trigger:
    platform: state
    entity_id: sensor.office_door_opening_sensor_access_control
    from: '23'
    to: '22'
  action:
    service: tts.google_say
    entity_id: "media_player.office"
    data:
      message: 'Welcome to the office!'

# Hallway door sensor

- alias: Turn hallway lights on door open
  trigger:
    platform: state
    entity_id: sensor.hallway_door_opening_sensor_access_control
    from: '23'
    to: '22'
  condition:
      condition: or  # 'when dark' condition: either after sunset or before sunrise - equivalent to a state condition on `sun.sun` of `below_horizon`
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
  action:
    - service: light.turn_on
      entity_id: light.hallway_lights
    - service: script.announce_everywhere
      data:
        message: 'Front door opened'

# Bathroom door sensor

- alias: Turn bathroom lights on door open
  trigger:
    platform: state
    entity_id: sensor.bathroom_door_opening_sensor_access_control
    from: '23'
    to: '22'
  action:
    service: light.turn_on
    entity_id: light.bathroom_lights

- alias: Say welcome on bathroom door open
  trigger:
    platform: state
    entity_id: sensor.bathroom_door_opening_sensor_access_control
    from: '23'
    to: '22'
  action:
    service: script.announce_everywhere
    data:
      message: 'Motion in bathroom!'

- alias: Turn off bathroom lights on door close if there is no motion inside
  trigger:
    platform: state
    entity_id: sensor.bathroom_door_opening_sensor_access_control
    from: '22'
    to: '23'
  condition:
    - condition: state
      entity_id: 'sensor.bathroom_multisensor_burglar'
      state: '0'
  action:
    service: light.turn_off
    entity_id: light.bathroom_lights


# Toilet door sensor

- alias: Turn toilet lights on door open
  trigger:
    platform: state
    entity_id: sensor.toilet_door_opening_sensor_access_control
    from: '23'
    to: '22'
  action:
    service: light.turn_on
    entity_id: light.toilet_lights


- alias: Say welcome on toilet door open
  trigger:
    platform: state
    entity_id: sensor.toilet_door_opening_sensor_access_control
    from: '23'
    to: '22'
  action:
    service: tts.google_say
    entity_id: "media_player.toilet"
    data:
      message: 'Welcome to the toilet!'


- alias: Turn off toilet lights on door close if there is no motion inside
  trigger:
    platform: state
    entity_id: sensor.toilet_door_opening_sensor_access_control
    from: '22'
    to: '23'
  condition:
    - condition: state
      entity_id: 'sensor.toilet_multisensor_burglar'
      state: '0'
  action:
    service: light.turn_off
    entity_id: light.toilet_lights
