# General

- alias: 'Turn off everything when everybody leaves home'
  trigger:
    - platform: state
      entity_id: group.all_persons
      to: 'not_home'
  action:
    service: script.turn_on
    entity_id: script.turn_off_everything

- alias: 'Say welcome Pawel when Pawel is back home'
  trigger:
    - platform: state
      entity_id: person.pawel
      to: 'home'
  action:
    service: script.announce_everywhere
    data:
      message: 'Welcome back Pawel!'

- alias: 'Say welcome Daria when Daria is back home'
  trigger:
    - platform: state
      entity_id: person.daria
      to: 'home'
  action:
    service: script.announce_everywhere
    data:
      message: 'Welcome back Daria!'
