# General

- alias: 'Turn off everything when everybody leaves home'
  trigger:
    - platform: state
      entity_id: zone.home
      to: 0
  action:
    - service: script.turn_off_everything
    - service: notify.level_note
      data:
        message: Turned off everything because everyone left home
        title: Everything turned off!
    - service: script.start_vacuum

- alias: 'Turn off vacuum when someone gets home'
  trigger:
    - platform: numeric_state
      entity_id: zone.home
      above: 0
  action:
    - service: script.stop_vacuum

- alias: 'Say welcome Pawel when Pawel is back home'
  trigger:
    - platform: state
      entity_id: person.pawel
      from: 'not_home'
      to: 'home'
  action:
    service: script.announce_everywhere
    data:
      message: 'Welcome back Pawel!'