- alias: "Stop kitchen strip effects when turned on"
  trigger:
    - platform: state
      entity_id: light.kitchen_cabinet_strip
      to: 'on'
    - platform: state
      entity_id: light.kitchen_island_strip
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: "{{ trigger.entity_id }}"
        effect: none
