# Media automations

- alias: Turn on DENON receiver and set it to Sonos input on Living room Sonos connect playing
  trigger:
    - platform: state
      entity_id: media_player.living_room
      to: 'playing'
  action:
      service: script.turn_on
      entity_id: script.set_denon_receiver_to_sonos_input

- alias: Turn off DENON receiver if its set to Sonos input on Living room Sonos connect stop playing
  trigger:
    - platform: state
      entity_id: media_player.living_room
      from: 'playing'
      for: "00:00:15" # only turn it off if not-playing holds for more than 15 seconds
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: '{{ state_attr("media_player.denon_avc_x6500h", "source") == "Sonos" }}'
      - condition: template
        value_template: '{{ state_attr("media_player.denon_avc_x6500h_avr", "source") == "Sonos" }}'
  action:
      service: script.turn_on
      entity_id: script.turn_off_denon_receiver
