# Hallway multisensor

- alias: Turn on hallway lights on motion when dark
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_multisensor_motion
      to: 'on'
    - platform: state
      entity_id: sensor.hallway_multisensor_burglar
      to: '8'
  condition:
      condition: or  # 'when dark' condition: either after sunset or before sunrise - equivalent to a state condition on `sun.sun` of `below_horizon`
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
  action:
    service: light.turn_on
    entity_id: light.hallway_lights

- alias: Turn off hallway lights when motion stops
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_multisensor_motion
      to: 'off'
    - platform: state
      entity_id: sensor.hallway_multisensor_burglar
      to: '0'
  action:
    service: light.turn_off
    entity_id: light.hallway_lights


# kitchen multisensor

- alias: Turn on kitchen lights on motion when dark
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_multisensor_motion
      to: 'on'
    - platform: state
      entity_id: sensor.kitchen_multisensor_burglar
      to: '8'
  condition:
      condition: or  # 'when dark' condition: either after sunset or before sunrise - equivalent to a state condition on `sun.sun` of `below_horizon`
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
  action:
    service: light.turn_on
    entity_id: light.kitchen_lights

- alias: Turn off kitchen lights when motion stops
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_multisensor_motion
      to: 'off'
    - platform: state
      entity_id: sensor.kitchen_multisensor_burglar
      to: '0'
  action:
    service: light.turn_off
    entity_id: light.kitchen_lights


# Toilet multisensor

- alias: Turn on toilet lights on motion
  trigger:
    - platform: state
      entity_id: binary_sensor.toilet_multisensor_motion
      to: 'on'
    - platform: state
      entity_id: sensor.toilet_multisensor_burglar
      to: '8'
  action:
    service: light.turn_on
    entity_id: light.toilet_lights

- alias: Turn off toilet lights when motion stops
  trigger:
    - platform: state
      entity_id: binary_sensor.toilet_multisensor_motion
      to: 'off'
    - platform: state
      entity_id: sensor.toilet_multisensor_burglar
      to: '0'
  action:
    service: light.turn_off
    entity_id: light.toilet_lights


# Bathroom multisensor

- alias: Turn on bathroom lights on motion
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_motion
      to: 'on'
  action:
    service: light.turn_on
    entity_id: light.bathroom_lights


- alias: Turn off bathroom lights when motion stops unless shower is in use
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_motion
      to: 'off'
  condition:
    - condition: state
      entity_id: 'binary_sensor.shower_in_use'
      state: 'off'
  action:
    service: light.turn_off
    entity_id: light.bathroom_lights


- alias: Turn off bathroom lights when shower is over unless there is motion
  trigger:
    platform: state
    entity_id: 'binary_sensor.shower_in_use'
    from: 'on'
    to: 'off'
  condition:
    - condition: state
      entity_id: 'binary_sensor.bathroom_motion'
      state: 'off'
  action:
    service: light.turn_off
    entity_id: light.bathroom_lights


- alias: Turn on bathroom mirror demister when shower is in use
  trigger:
    platform: state
    entity_id: 'binary_sensor.shower_in_use'
    from: 'off'
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.bathroom_mirror_switch_demister


- alias: Turn off bathroom mirror demister when shower is over
  trigger:
    platform: state
    entity_id: 'binary_sensor.shower_in_use'
    from: 'on'
    to: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.bathroom_mirror_switch_demister
