# Hallway multisensor

- alias: Turn on hallway lights on motion when dark
  trigger:
    platform: state
    entity_id: sensor.hallway_multisensor_burglar
    from: '0'
    to: '8'
  condition:
      condition: or  # 'when dark' condition: either after sunset or before sunrise - equivalent to a state condition on `sun.sun` of `below_horizon`
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
  action:
    service: light.turn_on
    entity_id: light.hallway_lights

- alias: Turn off hallway lights when motion stops
  trigger:
    platform: state
    entity_id: sensor.hallway_multisensor_burglar
    from: '8'
    to: '0'
  action:
    service: light.turn_off
    entity_id: light.hallway_lights


# kitchen multisensor

- alias: Turn on kitchen lights on motion when dark
  trigger:
    platform: state
    entity_id: sensor.kitchen_multisensor_burglar
    from: '0'
    to: '8'
  condition:
      condition: or  # 'when dark' condition: either after sunset or before sunrise - equivalent to a state condition on `sun.sun` of `below_horizon`
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
  action:
    service: light.turn_on
    entity_id: light.kitchen_lights

- alias: Turn off kitchen lights when motion stops
  trigger:
    platform: state
    entity_id: sensor.kitchen_multisensor_burglar
    from: '8'
    to: '0'
  action:
    service: light.turn_off
    entity_id: light.kitchen_lights


# Toilet multisensor

- alias: Turn on toilet lights on motion
  trigger:
    platform: state
    entity_id: sensor.toilet_multisensor_burglar
    from: '0'
    to: '8'
  action:
    service: light.turn_on
    entity_id: light.toilet_lights

- alias: Turn off toilet lights when motion stops
  trigger:
    platform: state
    entity_id: sensor.toilet_multisensor_burglar
    from: '8'
    to: '0'
  action:
    service: light.turn_off
    entity_id: light.toilet_lights


# Bathroom multisensor

- alias: Turn on bathroom lights on motion
  trigger:
    platform: state
    entity_id: sensor.bathroom_multisensor_burglar
    from: '0'
    to: '8'
  action:
    service: light.turn_on
    entity_id: light.bathroom_lights


- alias: Turn off bathroom lights when motion stops unless humidity is high
  trigger:
    platform: state
    entity_id: sensor.bathroom_multisensor_burglar
    from: '8'
    to: '0'
  condition:
    - condition: numeric_state
      entity_id: 'sensor.bathroom_multisensor_relative_humidity'
      below: 65
  action:
    service: light.turn_off
    entity_id: light.bathroom_lights


- alias: Turn off bathroom lights when humidity gets lower than 65 percent unless there is motion
  trigger:
    platform: numeric_state
    entity_id: sensor.bathroom_multisensor_relative_humidity
    below: 65
  condition:
    - condition: state
      entity_id: 'sensor.bathroom_multisensor_burglar'
      state: '0'
  action:
    service: light.turn_off
    entity_id: light.bathroom_lights
