# Hallway multisensor

- alias: Turn on hallway lights on motion when dark
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_multisensor_motion
      to: 'on'
  condition:
      condition: or  # 'when dark' condition: either after sunset or before sunrise - equivalent to a state condition on `sun.sun` of `below_horizon`
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
  action:
    action: script.turn_on_automatic_lights
    data:
      day_profile: script.set_hallway_lights_to_default
      night_lights:
        - light.hallway_strip
      night_mode: input_boolean.house_night_mode

- alias: Turn off hallway lights when motion stops
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_multisensor_motion
      to: 'off'
  action:
    service: light.turn_off
    entity_id: light.hallway_lights


# kitchen multisensor

- alias: Turn on kitchen lights on motion when dark
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_multisensor_motion
      to: 'on'
  condition:
      condition: or  # 'when dark' condition: either after sunset or before sunrise - equivalent to a state condition on `sun.sun` of `below_horizon`
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
  action:
    - action: script.turn_on_automatic_lights
      data:
        day_profile: script.set_kitchen_lights_to_default
        night_lights:
          - light.kitchen_cabinet_strip
          - light.kitchen_island_strip
        night_mode: input_boolean.house_night_mode
    - delay: "00:00:01"
    - service: script.normalize_kitchen_lifx_strips

- alias: Turn off kitchen lights when motion stops
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_multisensor_motion
      to: 'off'
  action:
    service: light.turn_off
    entity_id: light.kitchen_lights


# Toilet multisensor

- alias: Turn on toilet lights on motion
  trigger:
    - platform: state
      entity_id: binary_sensor.toilet_multisensor_motion
      to: 'on'
  action:
    action: script.turn_on_automatic_lights
    data:
      day_profile: script.set_toilet_lights_to_default
      night_lights:
        - light.toilet_strip
      night_mode: input_boolean.house_night_mode

- alias: Turn off toilet lights when motion stops
  trigger:
    - platform: state
      entity_id: binary_sensor.toilet_multisensor_motion
      to: 'off'
  action:
    service: light.turn_off
    entity_id: light.toilet_lights


# Bathroom multisensor

- alias: Turn on bathroom lights on motion
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_motion
      to: 'on'
  action:
    action: script.turn_on_automatic_lights
    data:
      day_profile: script.set_bathroom_lights_to_default
      night_lights:
        - light.bathroom_strip
      night_mode: input_boolean.house_night_mode


- alias: Turn off bathroom lights when motion stops unless shower is in use
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_motion
      to: 'off'
  condition:
    - condition: state
      entity_id: 'binary_sensor.shower_in_use'
      state: 'off'
  action:
    service: light.turn_off
    entity_id: light.bathroom_lights


- alias: Turn off bathroom lights when shower is over unless there is motion
  trigger:
    platform: state
    entity_id: 'binary_sensor.shower_in_use'
    from: 'on'
    to: 'off'
  condition:
    - condition: state
      entity_id: 'binary_sensor.bathroom_motion'
      state: 'off'
  action:
    service: light.turn_off
    entity_id: light.bathroom_lights


- alias: Turn on bathroom mirror demister when shower is in use
  trigger:
    platform: state
    entity_id: 'binary_sensor.shower_in_use'
    from: 'off'
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.bathroom_mirror_switch_demister


- alias: Turn off bathroom mirror demister when shower is over
  trigger:
    platform: state
    entity_id: 'binary_sensor.shower_in_use'
    from: 'on'
    to: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.bathroom_mirror_switch_demister
