- alias: Low battery notify
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      actions:
        - service: notify.level_note
          data:
            message: Devices {{sensors} are low on battery. Please change batteries!
            title: Low battery alert!
      time: '22:00:00'


- alias: Home Assistant Update Notification
  description: ''
  use_blueprint:
    path: >-
      forte/fancy-home-assistant-update-available-notifier-for-android-with-customizable-notification-settings.yaml
    input:
      clickAction: https://my.home-assistant.io/redirect/supervisor/
      delay: 0
      notify_device: 66f5dd0693351cc7d8db2a8c595f5f13
      include_hasspodcast: true


- alias: "Notify about completed download"
  trigger:
    platform: event
    event_type: transmission_downloaded_torrent
  action:
    - service: notify.level_note
      data:
        title: "Download completed!"
        message: "{{trigger.event.data.name}} has just been downloaded."


- alias: "Notify about started download"
  trigger:
    platform: event
    event_type: transmission_started_torrent
  action:
    - service: notify.level_note
      data:
        title: "Download started!"
        message: "{{trigger.event.data.name}} has just started downloading."

- id: vacuum_notifications
  alias: Vacuum Notifications
  trigger:
  - platform: state
    entity_id: vacuum.frank
  - platform: state
    entity_id: vacuum.frank
  condition:
    condition: template
    value_template: "{{ not (trigger.to_state.state == trigger.from_state.state) }}"
  action:
    - service: notify.level_info
      data:
        title: "Robot vacuum changed state!"
        message: >-
          "{{ trigger.to_state.name }} is {{ trigger.to_state.state }}"


- alias: "Birth control pill reminder"
  trigger:
    platform: time
    at: "19:00:00"
  action:
    - service: notify.level_important
      data:
        title: "Birth control pill reminder!"
        message: >-
          Daria, it's time to take your birth control pill! Daria, it's time
          to take your birth control pill! Daria, it's time to take your birth
          control pill!

- alias: "Morning vitamins reminder"
  trigger:
    platform: time
    at: "10:00:00"
  action:
    - service: notify.level_info
      data:
        title: "Morning vitamins reminder!"
        message: >-
          Pawel, it's time to take your morning vitamins!

- alias: "Lunch-time vitamins reminder"
  trigger:
    platform: time
    at: "14:00:00"
  action:
    - service: notify.level_info
      data:
        title: "Lunch-time vitamins reminder!"
        message: >-
          Pawel, it's time to take your lunch-time vitamins!

- alias: "Evening vitamins reminder"
  trigger:
    platform: time
    at: "23:30:00"
  action:
    - service: notify.level_info
      data:
        title: "Evening vitamins reminder!"
        message: >-
          Pawel, it's time to take your evening vitamins!
